# Generated by Django 3.1.2 on 2020-11-03 19:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id_aluno', models.AutoField(primary_key=True, serialize=False)),
                ('data_cadastro', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id_personalr', models.AutoField(primary_key=True, serialize=False)),
                ('data_cadastro', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_pessoa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('data_nascimento', models.DateField()),
                ('data_cadastro', models.DateField(default=django.utils.timezone.now)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telefone', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('N', 'Nenhuma das opções')], default='M', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoMedida',
            fields=[
                ('id_tipo_medida', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_medida', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id_unidade_medida', models.AutoField(primary_key=True, serialize=False)),
                ('unidade_medida', models.CharField(max_length=20)),
                ('sigla_unidade_medida', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalAluno',
            fields=[
                ('id_personal_aluno', models.AutoField(primary_key=True, serialize=False)),
                ('aluno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.aluno')),
                ('personal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.personal')),
            ],
        ),
        migrations.AddField(
            model_name='personal',
            name='Pessoa',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.pessoa'),
        ),
        migrations.CreateModel(
            name='MedidaAluno',
            fields=[
                ('id_medida_aluno', models.AutoField(primary_key=True, serialize=False)),
                ('valor_medida', models.FloatField()),
                ('data_registro', models.DateField()),
                ('aluno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.aluno')),
                ('personal_aluno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.personalaluno')),
                ('tipo_medida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.tipomedida')),
                ('unidade_medida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.unidademedida')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id_endereco', models.AutoField(primary_key=True, serialize=False)),
                ('rua', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=9)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('tipo_endereco', models.IntegerField(choices=[(1, 'Residencial'), (2, 'Aula')], default=1)),
                ('data_cadastro', models.DateField(default=django.utils.timezone.now)),
                ('pessoa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='Pessoa',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.pessoa'),
        ),
    ]
